# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4117e81480dbde1a46874cb307b5f99a1ae055c7c9680db354f766fae5172802b9044c8fbe5692d698e5f0567b7eefd57a4d95b584614a30d143e0ece6206e3f

test:
  secret_key_base: 19ca7bc61955e414297ce78974ffac7f1b4ac293cc3f5d6de2e83ad5e9f3a712681038b1d5c2df1c6e98e205c17a42f8b7abe672f2638c73caadf1aca5a44f2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
